### ISSUE TITLE
Support for utf-8 character encoding

### ISSUE THREAD

**Issue by hoof** [AOEpeople/geb-spock-reports#1]
Just like: https://github.com/renatoathaydes/spock-reports/issues/18
This plugin cannot handle tests containing special characters. I'm guessing  `spec-template.html` and `summary-template.html` should include `<meta charset="utf-8" />` in the header section.
Hope to see an update soon.

**Comment by tilmanginzel** [comment]
Hi @hoof,

I'll try to get to that as soon as possible, thanks for the hint!

**Comment by tilmanginzel** [comment]
@hoof I just published version 0.1.2 which fixes this issue.

**Comment by hoof** [comment]
Cool. I'll confirm asap, and get back to you.

**Comment by tilmanginzel** [comment]
Hey @hoof, have you had any chance to verify it?

**Comment by tilmanginzel** [comment]
I'm gonna close this for now as it should be resolved. Feel free to reopen if the issue still occurs. :)
