### ISSUE TITLE
In Jenkins html report pie chart is not showing

### ISSUE THREAD

**Issue by BalurQA** [AOEpeople/geb-spock-reports#19]
Hi, 
I liked this plugin very and I have integrated with my project.

Generated HTML report in Jenkins is not same as report generated in Local system. In Jenkins HTML report Pie chart is missing.

Is there any additional plugins needed in Jenkins to showing pie chart.

Thanks,
Balur

**Comment by tilmanginzel** [comment]
Hi @BalurQA, 

can you check and update your Jenkins [settings](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy) regarding the Content Security Policy? By default, execution of JavaScript and inline CSS (not used here) is not allowed in Jenkins. While I made sure that no resources are loaded from external urls and no inline CSS is used, I still required some JavaScript for the chart and some of the filter features.

Hope this helps :)

**Comment by tilmanginzel** [comment]
You could try setting the `default-src 'self'` value.

**Comment by BalurQA** [comment]
Hi @tilmanginzel ,

Thanks for quick response. Will give a try by setting `default-src 'self' ` value.

Will update in the result soon.

**Comment by tilmanginzel** [comment]
Hey @BalurQA, have you been able to update the Jenkins settings?

**Comment by BalurQA** [comment]
@tilmanginzel ,
Could you please tell me where in Jenkins I can update `default-src `.  I tried my self but I am not finding the file suggested in Jenkins folder.

**Comment by BalurQA** [comment]
@tilmanginzel : It is working fine now, I can see images in Jenkins report after setting default-src to safe. Thank you.

**Comment by tilmanginzel** [comment]
Awesome! Good to hear, that it works now. :)
