### ISSUE TITLE
test errors: support for printing stack traces

### ISSUE THREAD

**Issue by rosemead** [AOEpeople/geb-spock-reports#3]
Hi.
Would be great to be able to add stack traces of failures onto the generated report.

**Comment by tilmanginzel** [comment]
Hey @rosemead, I'll take a closer look at that when I find the time. I'm actually wondering why this does not work currently, but I will dig deeper.

**Comment by tilmanginzel** [comment]
I found a possible solution to access the stacktrace. I'll hope to publish a new version this or next week.

**Comment by tilmanginzel** [comment]
I just published release v0.1.4 which adds a toggle button to show the stacktrace. It's not quite beautiful, but in a future release I plan to make a full redesign of the report anyway.
