### ISSUE TITLE
Intermittent issues retrieving from Spring Libs Milestone

### ISSUE THREAD

**Issue by treyturner** [AOEpeople/geb-spock-reports#30]
Hi there,
My CI builds relying on geb-spock-reports 0.3.0-RC1 intermittently fail due to apparent issues pulling this library from Spring's milestone libs repo.

For instance, when I try to visit [https://repo.spring.io/libs-milestone/com/aoe/geb-spock-reports/](https://repo.spring.io/libs-milestone/com/aoe/geb-spock-reports/) right now, I get an empty directory.

![image](https://user-images.githubusercontent.com/1878152/99310406-9c395680-2820-11eb-8c82-fbf2751b8523.png)

Other times, accessing https://repo.spring.io/libs-milestone/com/aoe/geb-spock-reports/0.3.0-RC1/geb-spock-reports-0.3.0-RC1.pom seems to require authorization, which can be confirmed by visiting the link manually: I am presented with a username and password prompt (for which I have no credentials).

```
> Could not resolve all files for configuration ':example-ui-test:testCompileClasspath'.
   > Could not resolve com.aoe:geb-spock-reports:0.3.0-RC1.
     Required by:
         project :example-ui-test > net.company.qa:geb-spock:0.2.0
      > Could not resolve com.aoe:geb-spock-reports:0.3.0-RC1.
         > Could not get resource 'https://repo.spring.io/libs-milestone/com/aoe/geb-spock-reports/0.3.0-RC1/geb-spock-reports-0.3.0-RC1.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-milestone/com/aoe/geb-spock-reports/0.3.0-RC1/geb-spock-reports-0.3.0-RC1.pom'. Received status code 401 from server: Unauthorized
```

This happened a few weeks ago and the failure in CI was preventing a merge, so I temporarily disabled the pipeline so we could proceed. When I went to troubleshoot it a few days later, it was fixed without needing to change anything. Today I've found that it's resurfaced again.

I was just wondering if 0.3.0 might see a proper release soon (thereby becoming available in the release repo which is cached into my company's Artifactory), or if it could be mirrored to a more dependable repository.

**Comment by treyturner** [comment]
Update from Spring gitter chat:

```
Trey Turner @treyturner 11:18
I'm trying to figure out why the spring milestone repo is intermittently requesting authentication to pull artifacts. An example: https://repo.spring.io/libs-milestone/com/aoe/geb-spock-reports/0.3.0-RC1/geb-spock-reports-0.3.0-RC1.jar
I used to be able to pull this artifact without issue, but the required auth is breaking my builds :( If there's a better place to ask this, I'd appreciate some direction on where that would be

Brian Clozel @bclozel 11:38
We've applied permission changes to our artifact repositories. See https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020
The TL;DR; is while it was possible in the past, those repositories are not meant to mirror the entire content of public repositories. Relying on jcenter or maven central for those is a better option. Also in general, your apps should depend on repo.spring.io/milestone - as they should contain artifacts released by the spring team and this avoids duplicate resolution in your build. For related news and questions, you can follow/ask questions here: https://twitter.com/springops

Trey Turner @treyturner 11:48
hrm, as far as i know this is the only place this library is posted. i already opened a ticket yesterday with the developer asking if it could be published elsewhere. thanks for the info, i'll see what needs to be done.
```

**Comment by treyturner** [comment]
It appears I've found 0.3.0-RC1 on bintray here: https://bintray.com/aoepeople/libraries/geb-spock-reports/0.3.0-RC1 so now it's just a matter of figuring out where that's cached on my local Artifactory. It threw me off that mvnrepository only listed this artifact as available from Spring's Milestone repo: https://mvnrepository.com/artifact/com.aoe/geb-spock-reports?repo=spring-libs-milestone

**Comment by tilmanginzel** [comment]
Hi @treyturner, interesting, I have never heard of repo.spring.io before and don't know how this library got there in the first place. [Bintray](https://bintray.com/aoepeople/libraries/geb-spock-reports) is the only officially supported repository for geb-spock-reports, so using this to resolve it should be much more stable. :)
