### ISSUE TITLE
Images not Embedding when extending GebSpec 

### ISSUE THREAD

**Issue by seanfrenzel** [AOEpeople/geb-spock-reports#31]
As described reports will not be embedded when only extending GebSpec and need to extend GebReportingSpec to embed screenshots. This isn't documented on [renatoathaydes](https://github.com/renatoathaydes/spock-reports) project or this one and I had to troubleshoot to come to that conclusion. 

Please add the relevant documentation to express this requirement.

edit: removed irrelevant information with previously thought issues but feel free to comb through the edit history :)

**Comment by tilmanginzel** [comment]
Hi @seanfrenzel, thanks for the issue, that is a very good point I haven't thought about yet! I will update the readme in the coming days.

**Comment by tilmanginzel** [comment]
@seanfrenzel I have updated the readme accordingly. :) I am going to close this issue, but if you think that the explanation can be improved, feel free to reopen it!
