### ISSUE TITLE
jcenter shutdown

### ISSUE THREAD

**Issue by tmantis01** [AOEpeople/geb-spock-reports#32]
Hello,

the jcenter will shutdown (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Will this affect you? 
Because in the documentation you only use the jcenter repository.

**Comment by tilmanginzel** [comment]
Hi @tmantis01, sorry only got aware of this issue now. Yes, the shutdown will also affect this library. I am planning on migrating it to Maven Central in the coming weeks.

**Comment by tmantis01** [comment]
Thank you! :)

**Comment by treyturner** [comment]
Ack, just had pipelines start failing today as an apparent warning about this shutdown:
```
April 12th, 26th, 2021: We will have some short service brown-outs to remind users about the services that are going away on May 1st. (Specific hours will be advertised in the Bintray status page.)
```

**Comment by tilmanginzel** [comment]
Hi, all versions are now published to Sonatype / Maven Central: https://repo1.maven.org/maven2/com/aoe/geb-spock-reports/
