### ISSUE TITLE
html report: Wrap text in <div class="problem list">

### ISSUE THREAD

**Issue by rosemead** [AOEpeople/geb-spock-reports#7]
Currently, when a long, unbroken line is added to the report, text extends beyond the right edge of the browser window. In some cases (errors reported from the driver, quoting driver specs, capabilities), line is pretty long. Would be good to wrap that text to the size of the visible window.

**Comment by tilmanginzel** [comment]
Thanks, I will add this in the next version. Hopefully that won't take too long.

**Comment by tilmanginzel** [comment]
Hi, I just implemented the following solution:

The layout is fixed to the currently maximum width of 800px. `<pre>` tags with code blocks or stacktraces are now horizontally scrollable. I did not want to wrap these as code and stacktraces are pretty hard to read with numerous word/line wraps.

I'll probably publish the version today. ;)

**Comment by tilmanginzel** [comment]
Published in [v0.1.5](https://bintray.com/aoepeople/libraries/geb-spock-reports/0.1.5).
